#!/bin/bash

src=(
  main.cpp
  data/treap.cpp
  flow/matching.cpp
  flow/mcmf.cpp
  graph/scc.cpp
  string/strings.cpp
)
ps="$(mktemp)"
a2ps "${src[@]}" -2 --file-align=virtual --define=user.name="Adam Soltan" --prologue=color -o "$ps"
ps2pdf "$ps" lib.pdf
